version: "3"
services:
  pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /Users/trihoang/Desktop/kafka_streaming:/home/jovyan/work
    ports:
      - 8888:8888


